### ISSUE TITLE
New permissions are being required

### ISSUE THREAD

**Issue by qsona** [dai0304/pegmatite#33]
Hello, I'm using this awesome plugin. Thank you for your great work.

Yesterday (2020-01-05) the dialog for requiring new permissions was showed up.

<img width="442" alt="Screen Shot 2020-01-06 at 13 27 00" src="https://user-images.githubusercontent.com/1625314/71795608-636e1400-308a-11ea-8e76-b9691a1f73c4.png">

Is it by design? I didn't find a changelog, and I think this plugin needs permission for only visiting site so I'm afraid the new permissions are mistakenly being required.

**Comment by qsona** [comment]
I checked on the chrome://extensions page and tried to re-enabled it, then the following message was shown.

<img width="447" alt="Screen Shot 2020-01-06 at 13 50 03" src="https://user-images.githubusercontent.com/1625314/71795926-c90ed000-308b-11ea-9b92-d551fa198f84.png">

I'm a bit confusing because it's different from the first message 😂 sorry I don't know much about chrome extensions, so this is just a report. 🙇

**Comment by dai0304** [comment]
Hi.

I suspect this alert is caused by following change: 
https://github.com/dai0304/pegmatite/commit/49b3c0294d479f66dcad3ef9c318b57716f889fc#diff-49acb18b36376585351598abe4233856R6

But a change from `<all_urls>` to `https://*/*` is narrowing permissions, I think...
And new permission `tabs` is required by current design.

There is no intention to refer to browsing history...

I have opened a new PR that attempts to get narrower permissions.
https://github.com/dai0304/pegmatite/pull/34

CC: @dip-tadachi Do you have any feedback?

**Comment by dip-tadachi** [comment]
Hello @qsona, @dai0304 .

I'm sorry for worrying @qsona. 
Just as @dai0304 said.
This version has narrowing permission, and adding `tabs` permission.
Because ...

1. `<all_urls>` contains `http`, but only `https` is required. This is a tradeoff between maintainability and security.
2. `tabs` is required to listening for GitHub's page transitions (`pjax`) events. This is one of the #21 solutions.

Thank you.

**Comment by qsona** [comment]
Thank you for your reply! I was just a bit surprised because this plugin was disabled and the dialog was shown. I don't know why it was shown even though the permission had been narrowed (sorry I'm new to chrome extensions) but I understand it's safe. Thank you!

**Comment by DaisukeSudo** [comment]
Hi.
I'm sorry for the comment after closing 🙇

This is cause to the use of `tabs`.
However, I guess that this could be replaced to `activeTab`.
If this is possible, the warning should go away.

In my opinion, it can be changed by modifying as below.

``` js
if (tab.url.match(matches)) {

```
↓
``` js
if (tab.url && tab.url.match(matches)) {

```

https://github.com/dai0304/pegmatite/blob/develop/pegmatite/background.js#L54


I'm glad if you might consider it.
Thank you.
